[project]
name = "assignment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.17"
dependencies = [
    "httpx>=0.24.1",
    #"python-dotenv>=0.19.0",
    "rasa==3.6.21",
    "rasa-sdk==3.6.2",
    "reflex>=0.2.7",
    "requests>=2.32.4",
]
